name: Playwright Tests
on:
#  push:
#    branches: [ main, master ]
#  pull_request:
#    branches: [ main, master ]
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to (e.g., staging, production)'
        required: true
        type: choice
        options:
        - Staging
        - PROD
jobs:
  Job_1_Schedule-Trigger-Test-Staging:
    if: github.event.schedule == '30 16 * * *'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: Staging
    env:
        DEALERURL: ${{vars.DEV_DEALERURL}}
        DEALERUSERNAME: ${{ vars.DEV_DEALERUSERNAME }}
        DEALERPASSWORD: ${{ vars.DEV_DEALERPASSWORD }}
        DEALERNAME: ${{ vars.DEV_DEALERNAME }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Scheduller Trigger- Run Playwright tests
      run: DealerUrl='${{env.DEALERURL}}' DealerUserName='${{env.DEALERUSERNAME}}' DealerPassWord='${{env.DEALERPASSWORD}}' DealerName='${{env.DEALERNAME}}' npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ job.name }}
        path: playwright-report/
        retention-days: 30
        
  Job_2_Manually-Trigger-Test-Staging:
    if: github.event.inputs.environment == 'Staging'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
        DEALERURL: ${{vars.DEV_DEALERURL}}
        DEALERUSERNAME: ${{ vars.DEV_DEALERUSERNAME }}
        DEALERPASSWORD: ${{ vars.DEV_DEALERPASSWORD }}
        DEALERNAME: ${{ vars.DEV_DEALERNAME }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Scheduller Trigger - Run Playwright tests
      run: DealerUrl='${{env.DEALERURL}}' DealerUserName='${{env.DEALERUSERNAME}}' DealerPassWord='${{env.DEALERPASSWORD}}' DealerName='${{env.DEALERNAME}}' npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ job.name }}
        path: playwright-report/
        retention-days: 30
  
  deploy_Execution_Report:
    needs: Job_2_Manually-Trigger-Test-Staging  # Only deploy if the test job completes successfully
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Playwright Report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report-${{ job.name }}
          path: playwright-report

      - name: Deploy Playwright Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          publish_branch: gh-pages
